.TH "AnimationRange" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnimationRange \- Describes the start and end frame indices for a named animation sequence\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MD2\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstartFrame\fP"
.br
.RI "Index of first frame in the animation\&. "
.ti -1c
.RI "int \fBendFrame\fP"
.br
.RI "Index of last frame in the animation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Describes the start and end frame indices for a named animation sequence\&. 
.SH "Member Data Documentation"
.PP 
.SS "int AnimationRange::endFrame"

.PP
Index of last frame in the animation\&. 
.SS "int AnimationRange::startFrame"

.PP
Index of first frame in the animation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
