.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Animation/animation_system.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Animation/animation_system.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./ECS/entity_manager\&.hpp'\fP
.br
\fR#include 'MD2\&.hpp'\fP
.br
\fR#include '\&.\&./Rendering/mesh_renderer\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMD2Animator\fP"
.br
.RI "ECS component for animating an entity with an MD2 mesh\&. "
.ti -1c
.RI "class \fBAnimationSystem\fP"
.br
.RI "System responsible for updating MD2 animations for all entities with \fBMD2Animator\fP components\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
