.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/stb_image Directory Reference" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/stb_image Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstb_image\&.h\fP"
.br
.in -1c
