.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics Directory Reference" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAnimation\fP"
.br
.ti -1c
.RI "directory \fBMeshes\fP"
.br
.ti -1c
.RI "directory \fBRendering\fP"
.br
.ti -1c
.RI "directory \fBTexturing\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgraphics\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmodel_loading\&.hpp\fP"
.br
.in -1c
