.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Math Directory Reference" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Math Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmath\&.hpp\fP"
.br
.RI "Provides math utilities, vector/matrix types, transformation functions, and \fBAABB\fP logic using GLM\&. "
.in -1c
