.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src Directory Reference" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCamera\fP"
.br
.ti -1c
.RI "directory \fBECS\fP"
.br
.ti -1c
.RI "directory \fBEvents\fP"
.br
.ti -1c
.RI "directory \fBFSM\fP"
.br
.ti -1c
.RI "directory \fBGraphics\fP"
.br
.ti -1c
.RI "directory \fBMath\fP"
.br
.ti -1c
.RI "directory \fBPhysics\fP"
.br
.ti -1c
.RI "directory \fBProgram\fP"
.br
.ti -1c
.RI "directory \fBScripts\fP"
.br
.ti -1c
.RI "directory \fBstb_image\fP"
.br
.ti -1c
.RI "directory \fBTerrain\fP"
.br
.ti -1c
.RI "directory \fBtest\fP"
.br
.ti -1c
.RI "directory \fBTransform\fP"
.br
.ti -1c
.RI "directory \fBUtilities\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBassets\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconfiguration\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmirach\&.cpp\fP"
.br
.in -1c
