.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM Directory Reference" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommonStates\&.h\fP"
.br
.ti -1c
.RI "file \fBenemy\&.cpp\fP"
.br
.ti -1c
.RI "file \fBenemy\&.h\fP"
.br
.ti -1c
.RI "file \fBenemyState\&.cpp\fP"
.br
.RI "Implements enemy FSM behavior logic for all states: \fBAttack\fP, \fBFlee\fP, \fBPatrol\fP, \fBChase\fP, \fBDeath\fP, and \fBPain\fP\&. "
.ti -1c
.RI "file \fBenemyState\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEnemySystem\&.h\fP"
.br
.ti -1c
.RI "file \fBhoverEnemyState\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhoverEnemyState\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIEnemyStateLogic\&.h\fP"
.br
.ti -1c
.RI "file \fBsingleton\&.h\fP"
.br
.ti -1c
.RI "file \fBstate\&.h\fP"
.br
.ti -1c
.RI "file \fBStateMachine\&.h\fP"
.br
.in -1c
