.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Camera/camera.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Camera/camera.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Math/math\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.RI "A 3D camera that handles projection, view matrix generation, frustum culling, and orientation logic\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
