.TH "Collider" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collider \- Stores a pointer to the ReactPhysics3D collider\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <collider\&.hpp>\fP
.SH "Detailed Description"
.PP 
Stores a pointer to the ReactPhysics3D collider\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
