.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/collision_callback.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/collision_callback.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'physics\&.hpp'\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <set>\fP
.br
\fR#include '\&.\&./Scripts/health\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Animation/animation_system\&.hpp'\fP
.br
\fR#include '\&.\&./FSM/enemy\&.h'\fP
.br
\fR#include '\&.\&./FSM/CommonStates\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDamageContactCallback\fP"
.br
.RI "A physics collision callback that applies damage to entities hit by a thrown object\&. "
.ti -1c
.RI "class \fBEnemyAttackCallback\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
