.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/ECS/component_manager.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/ECS/component_manager.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'ecs_types\&.hpp'\fP
.br
\fR#include <unordered_map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComponentManager< ComponentType >\fP"
.br
.RI "Generic ECS Component Manager that maps entities to component data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
