.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/configuration.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/configuration.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'configuration\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconfiguration\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::string \fBconfiguration::asset_directory\fP = 'gameFiles'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
