.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/ECS/ecs_types.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/ECS/ecs_types.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBEntity\fP = uint32_t"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fBEntity\fP \fBINVALID_ENTITY\fP = static_cast<\fBEntity\fP>(\-1)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBEntity\fP = uint32_t"

.SH "Variable Documentation"
.PP 
.SS "\fBEntity\fP INVALID_ENTITY = static_cast<\fBEntity\fP>(\-1)\fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
