.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/enemy.h" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/enemy.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'StateMachine\&.h'\fP
.br
\fR#include '\&.\&./Math/math\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/physics_system\&.hpp'\fP
.br
\fR#include '\&.\&./ECS/entity_manager\&.hpp'\fP
.br
\fR#include 'CommonStates\&.h'\fP
.br
\fR#include '\&.\&./Graphics/Animation/animation_system\&.hpp'\fP
.br
\fR#include '\&.\&./Scripts/health\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemy\fP"
.br
.RI "Represents an enemy character controlled by a finite state machine (FSM)\&. This class defines properties, behavior, and state transitions for an enemy AI agent\&. It is integrated with ECS (Entity-Component System), physics, animation, and health systems\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
