.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/enemyState.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/enemyState.cpp \- Implements enemy FSM behavior logic for all states: \fBAttack\fP, \fBFlee\fP, \fBPatrol\fP, \fBChase\fP, \fBDeath\fP, and \fBPain\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'enemyState\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Implements enemy FSM behavior logic for all states: \fBAttack\fP, \fBFlee\fP, \fBPatrol\fP, \fBChase\fP, \fBDeath\fP, and \fBPain\fP\&. 

Each method controls state-specific behavior such as animation triggering, movement, and transitions\&. Uses Entity-Component-System (ECS), physics, and animation systems to perform AI logic\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
