.TH "ForceRaycast" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ForceRaycast \- Custom raycast callback to find the first dynamic body hit by a ray\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <raycast_callback\&.hpp>\fP
.PP
Inherits \fBPhysics::RaycastCallback\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBReportHit\fP (\fBPhysics::RigidBody\fP *body, float hitFraction) override"
.br
.RI "Callback function invoked when the ray hits a body\&. "
.in -1c

Public Member Functions inherited from \fBPhysics::RaycastCallback\fP
.in +1c
.ti -1c
.RI "virtual \fB~RaycastCallback\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPhysics::RigidBody\fP * \fBhitBody\fP = nullptr"
.br
.RI "Pointer to the first dynamic body hit\&. "
.in -1c
.SH "Detailed Description"
.PP 
Custom raycast callback to find the first dynamic body hit by a ray\&. 

Used for interaction systems (e\&.g\&., picking up objects)\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool ForceRaycast::ReportHit (\fBPhysics::RigidBody\fP * body, float hitFraction)\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Callback function invoked when the ray hits a body\&. 
.PP
\fBParameters\fP
.RS 4
\fIbody\fP The body hit by the ray\&. 
.br
\fIhitFraction\fP The fraction of the ray length at which the hit occurred\&. 
.RE
.PP
\fBReturns\fP
.RS 4
False to stop on the first dynamic hit, true to keep going otherwise\&. 
.RE
.PP

.PP
Implements \fBPhysics::RaycastCallback\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPhysics::RigidBody\fP* ForceRaycast::hitBody = nullptr"

.PP
Pointer to the first dynamic body hit\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
