.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Scripts/health.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Scripts/health.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHealth\fP"
.br
.ti -1c
.RI "struct \fBDead\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
