.TH "Health" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Health
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <health\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float Health::current"

.SS "float Health::max"


.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
