.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/IEnemyStateLogic.h" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/IEnemyStateLogic.h
.SH SYNOPSIS
.br
.PP
\fR#include 'enemy\&.h'\fP
.br
\fR#include '\&.\&./Physics/collision_callback\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIEnemyStateLogic\fP"
.br
.RI "Interface class defining all enemy state transition logic\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
