.TH "ImageData" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <image\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP = 0"
.br
.ti -1c
.RI "int \fBheight\fP = 0"
.br
.ti -1c
.RI "int \fBbpp\fP = 0"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBpixels\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int ImageData::bpp = 0"

.SS "int ImageData::height = 0"

.SS "std::vector<unsigned char> ImageData::pixels"

.SS "int ImageData::width = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
