.TH "InputEvent" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputEvent \- Structure holding abstracted input event data for use in the engine\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <input\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInputEventType\fP \fBtype\fP"
.br
.RI "Type of input event\&. "
.ti -1c
.RI "float \fBmouseDeltaX\fP = 0\&.0f"
.br
.RI "Change in mouse X since last event\&. "
.ti -1c
.RI "float \fBmouseDeltaY\fP = 0\&.0f"
.br
.RI "Change in mouse Y since last event\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure holding abstracted input event data for use in the engine\&. 
.SH "Member Data Documentation"
.PP 
.SS "float InputEvent::mouseDeltaX = 0\&.0f"

.PP
Change in mouse X since last event\&. 
.SS "float InputEvent::mouseDeltaY = 0\&.0f"

.PP
Change in mouse Y since last event\&. 
.SS "\fBInputEventType\fP InputEvent::type"

.PP
Type of input event\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
