.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/test/main.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/test/main.cpp \- Entry point of the Mirach engine\&. Initializes engine subsystems, loads assets, creates entities, and starts the main rendering loop\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'luaWrapper\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Entry point of the Mirach engine\&. Initializes engine subsystems, loads assets, creates entities, and starts the main rendering loop\&. 


.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
