.TH "MD2Header" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD2Header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBident\fP"
.br
.ti -1c
.RI "int32_t \fBversion\fP"
.br
.ti -1c
.RI "int32_t \fBskinWidth\fP"
.br
.ti -1c
.RI "int32_t \fBskinHeight\fP"
.br
.ti -1c
.RI "int32_t \fBframeSize\fP"
.br
.ti -1c
.RI "int32_t \fBnumSkins\fP"
.br
.ti -1c
.RI "int32_t \fBnumVertices\fP"
.br
.ti -1c
.RI "int32_t \fBnumTexCoords\fP"
.br
.ti -1c
.RI "int32_t \fBnumTriangles\fP"
.br
.ti -1c
.RI "int32_t \fBnumGLCmds\fP"
.br
.ti -1c
.RI "int32_t \fBnumFrames\fP"
.br
.ti -1c
.RI "int32_t \fBoffsetSkins\fP"
.br
.ti -1c
.RI "int32_t \fBoffsetTexCoords\fP"
.br
.ti -1c
.RI "int32_t \fBoffsetTriangles\fP"
.br
.ti -1c
.RI "int32_t \fBoffsetFrames\fP"
.br
.ti -1c
.RI "int32_t \fBoffsetGLCmds\fP"
.br
.ti -1c
.RI "int32_t \fBoffsetEnd\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int32_t MD2Header::frameSize"

.SS "int32_t MD2Header::ident"

.SS "int32_t MD2Header::numFrames"

.SS "int32_t MD2Header::numGLCmds"

.SS "int32_t MD2Header::numSkins"

.SS "int32_t MD2Header::numTexCoords"

.SS "int32_t MD2Header::numTriangles"

.SS "int32_t MD2Header::numVertices"

.SS "int32_t MD2Header::offsetEnd"

.SS "int32_t MD2Header::offsetFrames"

.SS "int32_t MD2Header::offsetGLCmds"

.SS "int32_t MD2Header::offsetSkins"

.SS "int32_t MD2Header::offsetTexCoords"

.SS "int32_t MD2Header::offsetTriangles"

.SS "int32_t MD2Header::skinHeight"

.SS "int32_t MD2Header::skinWidth"

.SS "int32_t MD2Header::version"


.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
