.TH "MD2Triangle" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD2Triangle \- Represents a single triangle using vertex and texture coordinate indices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MD2\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBvertexIndices\fP [3]"
.br
.RI "Indices into frame vertex arrays\&. "
.ti -1c
.RI "uint16_t \fBtexCoordIndices\fP [3]"
.br
.RI "Indices into texture coordinate array\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a single triangle using vertex and texture coordinate indices\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MD2Triangle::texCoordIndices[3]"

.PP
Indices into texture coordinate array\&. 
.SS "uint16_t MD2Triangle::vertexIndices[3]"

.PP
Indices into frame vertex arrays\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
