.TH "MD2TexCoord" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD2TexCoord \- Represents a texture coordinate in MD2 format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MD2\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBs\fP"
.br
.ti -1c
.RI "int16_t \fBt\fP"
.br
.RI "\fBTexture\fP coordinates (usually in pixels)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a texture coordinate in MD2 format\&. 
.SH "Member Data Documentation"
.PP 
.SS "int16_t MD2TexCoord::s"

.SS "int16_t MD2TexCoord::t"

.PP
\fBTexture\fP coordinates (usually in pixels)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
