.TH "MeshSkyDome::Vertex" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshSkyDome::Vertex \- Represents a single skydome vertex with 3D position and 2D texture coordinates\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector3f\fP \fBPos\fP"
.br
.RI "\fBVertex\fP position in world space\&. "
.ti -1c
.RI "\fBVector2f\fP \fBTex\fP"
.br
.RI "\fBTexture\fP coordinates (u, v)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a single skydome vertex with 3D position and 2D texture coordinates\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBVector3f\fP MeshSkyDome::Vertex::Pos"

.PP
\fBVertex\fP position in world space\&. 
.SS "\fBVector2f\fP MeshSkyDome::Vertex::Tex"

.PP
\fBTexture\fP coordinates (u, v)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
