.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/mesh3d.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/mesh3d.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./Utilities/utils\&.hpp'\fP
.br
\fR#include '\&.\&./Rendering/mesh_renderer\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./Math/math\&.hpp'\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include '\&.\&./Texturing/texture\&.hpp'\fP
.br
\fR#include '\&.\&./graphics\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMesh3D\fP"
.br
.RI "Abstract base class for rendering and managing 3D mesh data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
