.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/meshTerrain.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/meshTerrain.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mesh3d\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./Math/math\&.hpp'\fP
.br
\fR#include <vector>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeshTerrain\fP"
.br
.RI "Terrain mesh class using heightmap generation\&. "
.ti -1c
.RI "struct \fBMeshTerrain::Vertex\fP"
.br
.ti -1c
.RI "struct \fBMeshTerrain::TerrainPoint\fP"
.br
.RI "Structure representing a vertex on the terrain mesh\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
