.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/meshFile.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/meshFile.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./model_loading\&.hpp'\fP
.br
\fR#include 'mesh_entry\&.hpp'\fP
.br
\fR#include <string>\fP
.br
\fR#include 'mesh3d\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeshFile\fP"
.br
.RI "Represents a static 3D mesh loaded from file (e\&.g\&. OBJ, FBX, etc\&.) using Assimp\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
