.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/mesh_entry.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/mesh_entry.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMeshEntry\fP"
.br
.RI "Represents metadata about a submesh section of a 3D model\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
