.TH "MeshTerrain::TerrainPoint" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshTerrain::TerrainPoint \- Structure representing a vertex on the terrain mesh\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.ti -1c
.RI "bool \fBisEqual\fP (\fBTerrainPoint\fP &p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP = 0"
.br
.ti -1c
.RI "int \fBz\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a vertex on the terrain mesh\&. 

Point representation for fault generation\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool MeshTerrain::TerrainPoint::isEqual (\fBTerrainPoint\fP & p) const\fR [inline]\fP"

.SS "void MeshTerrain::TerrainPoint::Print ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int MeshTerrain::TerrainPoint::x = 0"

.SS "int MeshTerrain::TerrainPoint::z = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
