.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Rendering/mesh_renderer.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Rendering/mesh_renderer.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include '\&.\&./Texturing/texture\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./Math/math\&.hpp'\fP
.br
\fR#include '\&.\&./Meshes/mesh_entry\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMeshLOD\fP"
.br
.RI "Represents a single Level of Detail (LOD) variant of a mesh\&. "
.ti -1c
.RI "struct \fBMeshRenderer\fP"
.br
.RI "Holds all GPU and rendering information needed for rendering a mesh\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
