.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/meshSkyDome.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/meshSkyDome.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mesh3d\&.hpp'\fP
.br
\fR#include '\&.\&./\&.\&./Math/math\&.hpp'\fP
.br
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeshSkyDome\fP"
.br
.RI "A hemispherical skydome mesh used to render sky backgrounds\&. "
.ti -1c
.RI "struct \fBMeshSkyDome::Vertex\fP"
.br
.RI "Represents a single skydome vertex with 3D position and 2D texture coordinates\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
