.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/mirach.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/mirach.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Program/terrain_scene\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Main entry point of the engine\&. Initializes subsystems, loads models, sets up ECS, and runs the main loop\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main entry point of the engine\&. Initializes subsystems, loads models, sets up ECS, and runs the main loop\&. 
.PP
\fBReturns\fP
.RS 4
int Exit code\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
