.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/physics_system.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/physics_system.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'physics\&.hpp'\fP
.br
\fR#include '\&.\&./Transform/transform\&.hpp'\fP
.br
\fR#include '\&.\&./ECS/entity_manager\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Meshes/meshTerrain\&.hpp'\fP
.br
\fR#include '\&.\&./Math/math\&.hpp'\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhysicsSystem\fP"
.br
.RI "Manages physics simulation, including rigid body updates and collider handling, in the ECS framework\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
