.TH "Physics::Backend::RaycastAdapter" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::Backend::RaycastAdapter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_backend\&.hpp>\fP
.PP
Inherits rp3d::RaycastCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRaycastAdapter\fP (\fBPhysics::RaycastCallback\fP *cb)"
.br
.ti -1c
.RI "rp3d::decimal \fBnotifyRaycastHit\fP (const rp3d::RaycastInfo &info) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPhysics::RaycastCallback\fP * \fBuserCallback\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Physics::Backend::RaycastAdapter::RaycastAdapter (\fBPhysics::RaycastCallback\fP * cb)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "rp3d::decimal Physics::Backend::RaycastAdapter::notifyRaycastHit (const rp3d::RaycastInfo & info)\fR [inline]\fP, \fR [override]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBPhysics::RaycastCallback\fP* Physics::Backend::RaycastAdapter::userCallback"


.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
