.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/physics_backend.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/physics_backend.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'physics_backend\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhysics\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBWorld\fP > \fBPhysics::CreatePhysicsWorld\fP ()"
.br
.RI "Creates and returns a new physics world instance\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
