.TH "Physics::Ray" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::Ray \- Represents a ray used for raycasting\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRay\fP (const \fBVector3f\fP &s, const \fBVector3f\fP &e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector3f\fP \fBstart\fP"
.br
.RI "\fBRay\fP start point\&. "
.ti -1c
.RI "\fBVector3f\fP \fBend\fP"
.br
.RI "\fBRay\fP end point\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a ray used for raycasting\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Physics::Ray::Ray (const \fBVector3f\fP & s, const \fBVector3f\fP & e)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector3f\fP Physics::Ray::end"

.PP
\fBRay\fP end point\&. 
.SS "\fBVector3f\fP Physics::Ray::start"

.PP
\fBRay\fP start point\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
