.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Scripts/player_script.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Scripts/player_script.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ECS/entity_manager\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/physics_system\&.hpp'\fP
.br
\fR#include '\&.\&./Events/input_manager\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/physics\&.hpp'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayerScript\fP"
.br
.RI "Manages player-specific input, movement, jumping, and object interaction\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
