.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Scripts/player_script.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Scripts/player_script.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'player_script\&.hpp'\fP
.br
\fR#include '\&.\&./Transform/transform\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/raycast_callback\&.hpp'\fP
.br
\fR#include '\&.\&./Camera/camera\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/collision_callback\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
