.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/program.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/program.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'window\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/graphics\&.hpp'\fP
.br
\fR#include <string>\fP
.br
\fR#include <unordered_map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProgram\fP"
.br
.RI "Manages core SDL and OpenGL initialization, shader program creation, window rendering, and timing\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
