.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/program.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/program.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'program\&.hpp'\fP
.br
\fR#include 'time\&.hpp'\fP
.br
\fR#include <string>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
