.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/raycast_callback.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Physics/raycast_callback.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'physics\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGroundRaycast\fP"
.br
.RI "Custom raycast callback for detecting ground collisions\&. "
.ti -1c
.RI "class \fBForceRaycast\fP"
.br
.RI "Custom raycast callback to find the first dynamic body hit by a ray\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
