.TH "Rigidbody" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rigidbody \- Stores a pointer to the ReactPhysics3D rigid body\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <rigidbody\&.hpp>\fP
.SH "Detailed Description"
.PP 
Stores a pointer to the ReactPhysics3D rigid body\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
