.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/scene.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/scene.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.RI "Abstract base class for defining and managing a game scene lifecycle\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
