.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/singleton.h" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/singleton.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSingleton< T >\fP"
.br
.RI "A generic \fBSingleton\fP template class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
