.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/state.h" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/FSM/state.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState< T >\fP"
.br
.RI "Abstract base class representing a state in a finite state machine (FSM)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__STATE_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STATE_H"

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
