.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Terrain/terrain_manager.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Terrain/terrain_manager.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Graphics/Meshes/terrain_chunk\&.hpp'\fP
.br
\fR#include '\&.\&./ECS/entity_manager\&.hpp'\fP
.br
\fR#include '\&.\&./Transform/transform\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Rendering/mesh_renderer\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/physics_system\&.hpp'\fP
.br
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <mutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerrainManager\fP"
.br
.RI "Handles generation, GPU upload, and ECS/physics registration of terrain chunks\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
