.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/terrain_scene.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/terrain_scene.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'scene\&.hpp'\fP
.br
\fR#include 'program\&.hpp'\fP
.br
\fR#include '\&.\&./ECS/entity_manager\&.hpp'\fP
.br
\fR#include '\&.\&./Physics/physics_system\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Meshes/meshFile\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Meshes/meshTerrain\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Meshes/meshSkyDome\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Animation/MD2\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Animation/animation_system\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Rendering/healthBar\&.h'\fP
.br
\fR#include '\&.\&./Terrain/terrain_manager\&.hpp'\fP
.br
\fR#include '\&.\&./Camera/camera\&.hpp'\fP
.br
\fR#include 'lua_wrapper\&.h'\fP
.br
\fR#include '\&.\&./Scripts/player_script\&.hpp'\fP
.br
\fR#include '\&.\&./Scripts/health\&.hpp'\fP
.br
\fR#include '\&.\&./Graphics/Rendering/render_system\&.hpp'\fP
.br
\fR#include '\&.\&./FSM/enemy\&.h'\fP
.br
\fR#include '\&.\&./FSM/EnemySystem\&.h'\fP
.br
\fR#include '\&.\&./FSM/enemyState\&.hpp'\fP
.br
\fR#include '\&.\&./FSM/hoverEnemyState\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerrainScene\fP"
.br
.RI "A complete game scene that initializes, runs, and manages an interactive terrain environment with ECS, physics, and rendering\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
