.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/terrain_chunk.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Meshes/terrain_chunk.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'meshTerrain\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerrainChunk\fP"
.br
.RI "Represents a sub-section of a larger terrain for LOD or streaming\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
