.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Texturing/texture.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Graphics/Texturing/texture.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include 'texture\&.hpp'\fP
.br
\fR#include 'image\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
