.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/time.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/time.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <SDL3/SDL_timer\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTime\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBTime::GetTimeSeconds\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
