.TH "Time" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Time
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBGetTimeSeconds\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float Time::GetTimeSeconds ()\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
