.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Transform/transform.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Transform/transform.hpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Math/math\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransform\fP"
.br
.RI "Represents position, rotation, and scale of an object in 3D space\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
