.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Utilities/utils.hpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Utilities/utils.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARRAY_SIZE_IN_ELEMENTS\fP(a)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARRAY_SIZE_IN_ELEMENTS( a)"
\fBValue:\fP
.nf
(sizeof(a)/sizeof(a[0]))
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
