.TH "C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/window.cpp" 3 "Version 1.0" "MirachEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Documents/GitHub/ICT397-Project/mirachEngine/src/Program/window.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'window\&.hpp'\fP
.br
\fR#include <SDL3/SDL\&.h>\fP
.br
\fR#include <glad/gl\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWindowHandle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MirachEngine from the source code\&.
