var annotated_dup =
[
    [ "Physics", "namespace_physics.html", [
      [ "Backend", "namespace_physics_1_1_backend.html", [
        [ "ColliderBackend", "class_physics_1_1_backend_1_1_collider_backend.html", "class_physics_1_1_backend_1_1_collider_backend" ],
        [ "ContactListenerAdapter", "class_physics_1_1_backend_1_1_contact_listener_adapter.html", "class_physics_1_1_backend_1_1_contact_listener_adapter" ],
        [ "RaycastAdapter", "class_physics_1_1_backend_1_1_raycast_adapter.html", "class_physics_1_1_backend_1_1_raycast_adapter" ],
        [ "RigidBodyBackend", "class_physics_1_1_backend_1_1_rigid_body_backend.html", "class_physics_1_1_backend_1_1_rigid_body_backend" ],
        [ "WorldBackend", "class_physics_1_1_backend_1_1_world_backend.html", "class_physics_1_1_backend_1_1_world_backend" ]
      ] ],
      [ "Collider", "class_physics_1_1_collider.html", "class_physics_1_1_collider" ],
      [ "CollisionCallback", "class_physics_1_1_collision_callback.html", "class_physics_1_1_collision_callback" ],
      [ "Ray", "class_physics_1_1_ray.html", "class_physics_1_1_ray" ],
      [ "RaycastCallback", "class_physics_1_1_raycast_callback.html", "class_physics_1_1_raycast_callback" ],
      [ "RigidBody", "class_physics_1_1_rigid_body.html", "class_physics_1_1_rigid_body" ],
      [ "World", "class_physics_1_1_world.html", "class_physics_1_1_world" ]
    ] ],
    [ "AABB", "struct_a_a_b_b.html", "struct_a_a_b_b" ],
    [ "AnimationRange", "struct_animation_range.html", "struct_animation_range" ],
    [ "AnimationSystem", "class_animation_system.html", "class_animation_system" ],
    [ "Attack", "class_attack.html", "class_attack" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "Chase", "class_chase.html", "class_chase" ],
    [ "Collider", "struct_collider.html", null ],
    [ "Color", "struct_color.html", "struct_color" ],
    [ "ComponentManager", "class_component_manager.html", "class_component_manager" ],
    [ "DamageContactCallback", "class_damage_contact_callback.html", "class_damage_contact_callback" ],
    [ "Dead", "struct_dead.html", null ],
    [ "Death", "class_death.html", "class_death" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "EnemyAttackCallback", "class_enemy_attack_callback.html", "class_enemy_attack_callback" ],
    [ "enemyState", "classenemy_state.html", "classenemy_state" ],
    [ "EnemySystem", "class_enemy_system.html", "class_enemy_system" ],
    [ "EntityManager", "class_entity_manager.html", "class_entity_manager" ],
    [ "Flee", "class_flee.html", "class_flee" ],
    [ "ForceRaycast", "class_force_raycast.html", "class_force_raycast" ],
    [ "GroundRaycast", "class_ground_raycast.html", "class_ground_raycast" ],
    [ "Health", "struct_health.html", "struct_health" ],
    [ "HealthBarRenderer", "class_health_bar_renderer.html", "class_health_bar_renderer" ],
    [ "hoverEnemyState", "classhover_enemy_state.html", "classhover_enemy_state" ],
    [ "IEnemyStateLogic", "class_i_enemy_state_logic.html", "class_i_enemy_state_logic" ],
    [ "ImageData", "struct_image_data.html", "struct_image_data" ],
    [ "InputEvent", "struct_input_event.html", "struct_input_event" ],
    [ "InputManager", "class_input_manager.html", "class_input_manager" ],
    [ "MD2Animator", "struct_m_d2_animator.html", "struct_m_d2_animator" ],
    [ "MD2Frame", "struct_m_d2_frame.html", "struct_m_d2_frame" ],
    [ "MD2Header", "struct_m_d2_header.html", "struct_m_d2_header" ],
    [ "MD2TexCoord", "struct_m_d2_tex_coord.html", "struct_m_d2_tex_coord" ],
    [ "MD2Triangle", "struct_m_d2_triangle.html", "struct_m_d2_triangle" ],
    [ "MD2Vertex", "struct_m_d2_vertex.html", "struct_m_d2_vertex" ],
    [ "Mesh3D", "class_mesh3_d.html", "class_mesh3_d" ],
    [ "MeshEntry", "struct_mesh_entry.html", "struct_mesh_entry" ],
    [ "MeshFile", "class_mesh_file.html", "class_mesh_file" ],
    [ "MeshLOD", "struct_mesh_l_o_d.html", "struct_mesh_l_o_d" ],
    [ "MeshMD2", "class_mesh_m_d2.html", "class_mesh_m_d2" ],
    [ "MeshRenderer", "struct_mesh_renderer.html", "struct_mesh_renderer" ],
    [ "MeshSkyDome", "class_mesh_sky_dome.html", "class_mesh_sky_dome" ],
    [ "MeshTerrain", "class_mesh_terrain.html", "class_mesh_terrain" ],
    [ "Pain", "class_pain.html", "class_pain" ],
    [ "Patrol", "class_patrol.html", "class_patrol" ],
    [ "PhysicsSystem", "class_physics_system.html", "class_physics_system" ],
    [ "PlayerScript", "class_player_script.html", "class_player_script" ],
    [ "Program", "class_program.html", "class_program" ],
    [ "Rigidbody", "struct_rigidbody.html", null ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "Singleton", "class_singleton.html", "class_singleton" ],
    [ "State", "class_state.html", "class_state" ],
    [ "StateMachine", "class_state_machine.html", "class_state_machine" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "TerrainChunk", "class_terrain_chunk.html", "class_terrain_chunk" ],
    [ "TerrainManager", "class_terrain_manager.html", "class_terrain_manager" ],
    [ "TerrainScene", "class_terrain_scene.html", "class_terrain_scene" ],
    [ "Texture", "class_texture.html", "class_texture" ],
    [ "Transform", "class_transform.html", "class_transform" ],
    [ "WindowHandle", "struct_window_handle.html", "struct_window_handle" ]
];